In [1]:
import pandas as pd
import numpy as np
from sklearn.multioutput import MultiOutputClassifier
from sklearn.feature_selection import SelectFromModel

In [2]:
data= pd.read_csv('diabetes.csv')

In [3]:
data.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [4]:
n=99000
data.drop(data.tail(n).index,
        inplace = True)

In [5]:
data.drop('gender',inplace=True,axis=1)

In [6]:
data.drop('age',inplace=True,axis=1)

In [7]:
data['hypertension'].unique()

array([0, 1], dtype=int64)

In [8]:
data1=pd.read_csv('Heart.csv')

In [9]:
data1

age     sex               cp  trtbps  chol    fbs      rest_ecg  \
0     63    Male     Asymptomatic     145   233   True        Normal   
1     37    Male  Atypical Angina     130   250  False  ST Elevation   
2     41  Female   Typical Angina     130   204  False        Normal   
3     56    Male   Typical Angina     120   236  False  ST Elevation   
4     57  Female       Non-Angina     120   354  False  ST Elevation   
..   ...     ...              ...     ...   ...    ...           ...   
298   57  Female       Non-Angina     140   241  False  ST Elevation   
299   45    Male     Asymptomatic     110   264  False  ST Elevation   
300   68    Male       Non-Angina     144   193   True  ST Elevation   
301   57    Male       Non-Angina     130   131  False  ST Elevation   
302   57  Female   Typical Angina     130   236  False        Normal   

     thalachh exng  oldpeak       slope  ca  thall  target  
0         150   No      2.3        Flat   0      1       1  
1         187   No      3.5  Up Sloping   0      2       1  
2         172   No      1.4        Flat   0      2       1  
3         178   No      0.8        Flat   0      2       1  
4         163  Yes      0.6        Flat   0      2       1  
..        ...  ...      ...         ...  ..    ...     ...  
298       123  Yes      0.2  Up Sloping   0      3       0  
299       132   No      1.2  Up Sloping   0      3       0  
300       141   No      3.4  Up Sloping   2      3       0  
301       115  Yes      1.2  Up Sloping   1      3       0  
302       174   No      0.0  Up Sloping   1      2       0  

[303 rows x 14 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
sex = le.fit_transform(data1['sex'])
data1['sex']=sex
cp= le.fit_transform(data1['cp'])
fbs=le.fit_transform(data1['fbs'])
rest_ecg=le.fit_transform(data1['rest_ecg'])
exng=le.fit_transform(data1['exng'])
slope=le.fit_transform(data1['slope'])
smoking_history=le.fit_transform(data['smoking_history'])
data1['sex']=sex
data1['cp']=cp
data1['fbs']=fbs
data1['rest_ecg']=rest_ecg
data1['exng']=exng
data1['slope']=slope
data['smoking_history']=smoking_history

In [11]:
data1.rename(columns={'target': 'heart_disease'}, inplace=True)

In [12]:
data1

age  sex  cp  trtbps  chol  fbs  rest_ecg  thalachh  exng  oldpeak  \
0     63    1   0     145   233    1         1       150     0      2.3   
1     37    1   1     130   250    0         2       187     0      3.5   
2     41    0   3     130   204    0         1       172     0      1.4   
3     56    1   3     120   236    0         2       178     0      0.8   
4     57    0   2     120   354    0         2       163     1      0.6   
..   ...  ...  ..     ...   ...  ...       ...       ...   ...      ...   
298   57    0   2     140   241    0         2       123     1      0.2   
299   45    1   0     110   264    0         2       132     0      1.2   
300   68    1   2     144   193    1         2       141     0      3.4   
301   57    1   2     130   131    0         2       115     1      1.2   
302   57    0   3     130   236    0         1       174     0      0.0   

     slope  ca  thall  heart_disease  
0        1   0      1              1  
1        2   0      2              1  
2        1   0      2              1  
3        1   0      2              1  
4        1   0      2              1  
..     ...  ..    ...            ...  
298      2   0      3              0  
299      2   0      3              0  
300      2   2      3              0  
301      2   1      3              0  
302      2   1      2              0  

[303 rows x 14 columns]

In [13]:
datahd=data1.merge(data, on='heart_disease',how='right')

In [14]:
datahd.head()

age  sex  cp  trtbps  chol  fbs  rest_ecg  thalachh  exng  oldpeak  slope  \
0   63    1   0     145   233    1         1       150     0      2.3      1   
1   37    1   1     130   250    0         2       187     0      3.5      2   
2   41    0   3     130   204    0         1       172     0      1.4      1   
3   56    1   3     120   236    0         2       178     0      0.8      1   
4   57    0   2     120   354    0         2       163     1      0.6      1   

   ca  thall  heart_disease  hypertension  smoking_history    bmi  \
0   0      1              1             0                4  25.19   
1   0      2              1             0                4  25.19   
2   0      2              1             0                4  25.19   
3   0      2              1             0                4  25.19   
4   0      2              1             0                4  25.19   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                  140         0  
2          6.6                  140         0  
3          6.6                  140         0  
4          6.6                  140         0

In [15]:
datahd.shape

(138864, 20)

In [16]:
n=100000
datahd.drop(datahd.tail(n).index,
        inplace = True)
 

In [17]:
x = datahd.drop(['heart_disease', 'diabetes'], axis=1)

In [18]:
x

age  sex  cp  trtbps  chol  fbs  rest_ecg  thalachh  exng  oldpeak  \
0       63    1   0     145   233    1         1       150     0      2.3   
1       37    1   1     130   250    0         2       187     0      3.5   
2       41    0   3     130   204    0         1       172     0      1.4   
3       56    1   3     120   236    0         2       178     0      0.8   
4       57    0   2     120   354    0         2       163     1      0.6   
...    ...  ...  ..     ...   ...  ...       ...       ...   ...      ...   
38859   62    0   2     138   294    1         2       106     0      1.9   
38860   67    1   2     100   299    0         1       125     1      0.9   
38861   59    1   0     160   273    0         1       125     0      0.0   
38862   45    1   2     142   309    0         1       147     1      0.0   
38863   58    1   2     128   259    0         1       130     1      3.0   

       slope  ca  thall  hypertension  smoking_history    bmi  HbA1c_level  \
0          1   0      1             0                4  25.19          6.6   
1          2   0      2             0                4  25.19          6.6   
2          1   0      2             0                4  25.19          6.6   
3          1   0      2             0                4  25.19          6.6   
4          1   0      2             0                4  25.19          6.6   
...      ...  ..    ...           ...              ...    ...          ...   
38859      2   3      2             0                0  21.06          6.6   
38860      2   2      2             0                0  21.06          6.6   
38861      1   0      2             0                0  21.06          6.6   
38862      2   3      3             0                0  21.06          6.6   
38863      2   2      3             0                0  21.06          6.6   

       blood_glucose_level  
0                      140  
1                      140  
2                      140  
3                      140  
4                      140  
...                    ...  
38859                  160  
38860                  160  
38861                  160  
38862                  160  
38863                  160  

[38864 rows x 18 columns]

In [19]:
y=datahd[['diabetes','heart_disease']]

In [20]:
datahd['heart_disease'].unique()

array([1, 0], dtype=int64)

In [21]:
y

diabetes  heart_disease
0             0              1
1             0              1
2             0              1
3             0              1
4             0              1
...         ...            ...
38859         0              0
38860         0              0
38861         0              0
38862         0              0
38863         0              0

[38864 rows x 2 columns]

In [22]:
import pickle
from sklearn.model_selection import cross_val_score, train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score , precision_score , recall_score

In [23]:
from sklearn.model_selection import train_test_split ,RandomizedSearchCV

In [24]:
X_train,x_test,Y_train,y_test=train_test_split(x,y,random_state=20,test_size=0.40)

ALOGRITHM BUILDER

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
model1= RandomForestClassifier(n_estimators=100, random_state=42

)
model = MultiOutputClassifier(model1)

In [27]:
model.fit(X_train,Y_train)

MultiOutputClassifier(estimator=RandomForestClassifier(random_state=42))

In [28]:
y_pred=model.predict(x_test)

In [29]:
acc = accuracy_score(y_test, model.predict(x_test)) * 100

In [30]:
acc

99.98070243149363

In [31]:
precision = precision_score(y_test, y_pred, average='macro')

In [32]:
recall = recall_score(y_test, y_pred, average='macro')

In [33]:
file_name='HD.pkl'
pickle.dump(model,open(file_name,'wb'))

In [34]:
loaded=pickle.load(open(file_name,'rb'))
result=loaded.score(x_test,y_test)

In [35]:
result

0.9998070243149363

In [36]:
x

age  sex  cp  trtbps  chol  fbs  rest_ecg  thalachh  exng  oldpeak  \
0       63    1   0     145   233    1         1       150     0      2.3   
1       37    1   1     130   250    0         2       187     0      3.5   
2       41    0   3     130   204    0         1       172     0      1.4   
3       56    1   3     120   236    0         2       178     0      0.8   
4       57    0   2     120   354    0         2       163     1      0.6   
...    ...  ...  ..     ...   ...  ...       ...       ...   ...      ...   
38859   62    0   2     138   294    1         2       106     0      1.9   
38860   67    1   2     100   299    0         1       125     1      0.9   
38861   59    1   0     160   273    0         1       125     0      0.0   
38862   45    1   2     142   309    0         1       147     1      0.0   
38863   58    1   2     128   259    0         1       130     1      3.0   

       slope  ca  thall  hypertension  smoking_history    bmi  HbA1c_level  \
0          1   0      1             0                4  25.19          6.6   
1          2   0      2             0                4  25.19          6.6   
2          1   0      2             0                4  25.19          6.6   
3          1   0      2             0                4  25.19          6.6   
4          1   0      2             0                4  25.19          6.6   
...      ...  ..    ...           ...              ...    ...          ...   
38859      2   3      2             0                0  21.06          6.6   
38860      2   2      2             0                0  21.06          6.6   
38861      1   0      2             0                0  21.06          6.6   
38862      2   3      3             0                0  21.06          6.6   
38863      2   2      3             0                0  21.06          6.6   

       blood_glucose_level  
0                      140  
1                      140  
2                      140  
3                      140  
4                      140  
...                    ...  
38859                  160  
38860                  160  
38861                  160  
38862                  160  
38863                  160  

[38864 rows x 18 columns]

In [37]:
input_data=(63,1,0,145,233,1,1,100,0,2.3,0,1,1, 1, 3, 33.5, 9.2, 90)
data_point = (35, 1, 0, 120, 180, 0, 1, 100, 0, 0.5, 1, 0, 2, 0, 0, 22.5, 5.2, 90)
data_point1 = (42, 1, 0, 125, 190, 1, 1, 160, 0, 0.8, 1, 0, 2, 0, 1, 28.5, 7.2, 160)
data_point2 = (63,0,0,145,240,1,1,100,0,2.3,0,1,1,1,4,25.5,6.2,90)


In [38]:
input_d=np.asarray(input_data)
data_point=np.asarray(data_point)
data_point2=np.asarray(data_point2)
data_point1=np.asarray(data_point1)
reshaped=input_d.reshape(1,-1)
a=data_point.reshape(1,-1)
b=data_point2.reshape(1,-1)
c=data_point1.reshape(1,-1)

In [39]:
prediction=model.predict(reshaped)
predictio=model.predict(a)
predicti=model.predict(b)
predict=model.predict(c)

c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\Kanimozhi N\anaconda3

In [40]:
print(prediction)
print(predicti)
print(predictio)
print(predict)

[[1 0]]
[[0 1]]
[[0 0]]
[[1 1]]


In [126]:
y

diabetes  heart_disease
0             0              1
1             0              1
2             0              1
3             0              1
4             0              1
...         ...            ...
38859         0              0
38860         0              0
38861         0              0
38862         0              0
38863         0              0

[38864 rows x 2 columns]

In [41]:
x.shape

(38864, 18)

In [205]:
from sklearn.metrics import classification_report, confusion_matrix

In [207]:

print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99      1425
           1       1.00      1.00      1.00       657

   micro avg       1.00      0.98      0.99      2082
   macro avg       1.00      0.99      0.99      2082
weighted avg       1.00      0.98      0.99      2082
 samples avg       0.12      0.12      0.12      2082



c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Kanimozhi N\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
